### PR TITLE
Added About Us Page

### PR DESCRIPTION
**Pull request by VerisimilitudeX**

### CODE REVIEW

**Comment by Nv7-GitHub** [comment]
@Verisimilitude11 Svelte doesn't use head and body tags

**Comment by Nv7-GitHub** [comment]
also pls dont merge without a review from me next time

**Comment by VerisimilitudeX** [comment]
👍👍 Sounds good, sorry nishant

**Comment by VerisimilitudeX** [comment]
👍👍 Sounds good, sorry nishant

**Pull request merged**
